CREATE TABLE public.documents (
    id bigint PRIMARY KEY,
    text text,
    metadata jsonb,
    embedding vector(1536)
);

CREATE TABLE public.qa (
    "вопрос" text,
    "ответ" text
);

CREATE TABLE public.Nonanswered_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT now(),
    question text,
    username text,
    telegram_id integer,
    phone_number text
);
